### ISSUE TITLE
Parse back Date types 

### ISSUE THREAD

**Issue by yacine-karim** [deniskabana/react-persistent-state-hook#1]
i have set a filter:

exemple 
```
objectInLocalStorage {
      date:"2023-10-30T00:00:00.000Z"
}
```

but when object was loaded back it was loaded as string and not as a Date

additional informations :
i'm also using the Date.prototype.toJSON to override the behavior :
```
Date.prototype.toJSON = function() {
    return this.toISOString(); 
};
```

**Comment by deniskabana** [comment]
Hello, @yacine-karim 

Thank you for reporting this bug! I currently have a local branch with some changes to be merged back, I will inspect the issue and fix it in main. I'll let you know by closing this issue.

**Comment by deniskabana** [comment]
@yacine-karim Sorry for the late response, battling some health issues.

I tried multiple options to perform this case and unfortunately, the current implementation relies on `parse()` and `stringify()` methods of `JSON` API.

Running a quick dirty test showed me that Date isn't really easy to parse or determine.
```
> JSON.parse(JSON.stringify(new Date()))
'2023-11-28T07:09:38.053Z'
```

---

Here's a quick solution for you:
```
const [dateIsoString, setDateIsoString] = usePersistentState<string>(value.toISOString())
const date = new Date(dateIsoString)
```

_Note: A potential future update might be to implement different internal parsers for different data types. Given this reported bug, I am closing this issue as it will not be resolved in the library since it is usage dependent._
